### ISSUE TITLE
Write/read sbyte does not support full range (-128 in particular)

### ISSUE THREAD

**Issue by jaeksmith** [Xytabich/UNet#2]
In order to support full sbyte range (-128 to 127) - instead of just -127 to 127, you could--

In WriteSByte, instead of--
buffer[index] = (byte)(value < 0 ? (value + 0xFF) : value);
do--
buffer[index] = (byte)(value < 0 ? (value + 0x100) : value);
// -1 gets encoded as 0xFF, -128 gets encoded as 0x80,

And In ReadSByte, instead of--
if(value > 0x80) value = value - 0xFF;
do--
if(value >= 0x80) value = value - 0x100;
// Note the >= mod so that 0x80 properly decodes as -128 instead of exception...

Thanks

**Comment by Xytabich** [comment]
Thanks for finding the bug, released new version with a fix https://github.com/Xytabich/UNet/releases/tag/u2.0.1
